networks:
  default:
    driver: bridge

volumes:
  mongo:

services:
  aipom:
    build: .
    env_file: .env
    networks:
      - default
    ports:
      - 8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file: .env
    networks:
      - default
    volumes:
      - mongo:/data/db
