networks:
  default:
    driver: bridge

volumes:
  mongo-data:

services:
  aipom:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node
    volumes:
      - ..:/workspaces/aipom:cached
    networks:
      - default
    command: sleep infinity

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - default
    env_file: ../.env
