volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file: .env
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
